# http://www.tagblender.net/
hashtags = {
    'top30': '#love #instagood #me #cute #tbt #photooftheday #instamood #iphonesia #tweegram #picoftheday #igers #girl #beautiful #instadaily #summer #instagramhub #iphoneonly #follow #igdaily #bestoftheday #happy #picstitch #jj #sky #nofilter #fashion #followme #fun #sun #vsco',
    'top60': '#smile #instagramers #pretty #food #friends #like #lol #nature #hair #onedirection #swag #beach #funny #bored #life #cool #blue #dog #pink #art #versagram #sunset #hot #photo #instahub #my #family #throwbackthursday #cat #vsco',
    'top90': '#amazing #girls #awesome #clouds #baby #party #red #repost #music #black #jj_forum #instalove #all_shots #igaddict #night #followback #yummy #white #bestfriend #green #yum #instago #halloween #school #eyes #harrystyles #sweet #vsco',
    'flcs': '#f4f #s4s #l4l #c4c #likeforlike #likeall #like4like #likes4likes #liking #instagood #follow #followme #followback #followforfollow #follow4follow #followers #followher #follower #followhim #followbackteam #followall #comment #comments #commentback #comment4comment #commentbelow #shoutout #shoutouts #shoutoutback #vsco',
    'followme': '#follow #followme #followback #followforfollow #follow4follow #followers #followher #follower #followhim #followbackteam #followall #followbackalways #follows #following #followgram #followalways #followstagram #followshoutoutlikecomment #follownow #followus #followmefollowyou #followmeplease #followbackinstantly #f4f #followmeback #followyou #followforlike #ifollowback #ifollow #vsco',
    'nature': '#weather #skylovers #natureporn #amazing #skypainters #gf_daily #light #fantastic #green #trees #beautiful #iphonesia #naturelovers #sunset #clouds #beach #photooftheday #summer #tree #instadaily #cloud #cloudporn #natureza #mothernature #beauty #dusk #red #pretty #nature_seekers #vsco',
    'art': '#art #artist #artistic #artists #arte #dibujo #myart #artwork #illustration #graphicdesign #graphic #color #colour #colorful #painting #drawing #drawings #markers #paintings #watercolor #watercolour #ink #creative #sketch #sketchaday #pencil #cs6 #photoshop #beautiful #vsco',
    'photo': '#photography #photo #photos #tagsblender #pic #pics #art #artist #artistic #artists #arte #dibujo #myart #artwork #color #all_shots #exposure #composition #focus #capture #classical #clean #beautiful #perfect #shiny #amazing #best #colorful #illustration #vsco',
    'gm': '#goodmorning #morning #mornings #good #breakfast #getup #early #sunrise #sun #sunlight #coffee #work #dresses #blanket #cold #winter #rainy #stunning #beautiful #holiday #saturday #dayoff #lingoware #deepsleep #warm #love #fatigue #goodday #sweet #vsco',
    'gn': '#beds #bed #goodnight #photooftheday #star #instagood #nightynight #beautiful #kisses #stars #love #instagoodnight #sleeptime #bedtime #nights #hugs #goodday #moonlight #fullmoon #sleepy #mybde #nighttime #lightsout #dark #night #moon #gn #blanket #drunk #vsco',
    'love': '#loveudad #mylove #lovehim #tolove #loveher #lov #loveubro #lovers #lovemybf #inlove #lovelyday #love4love #lovley #freelove #loveme #nolove #lovemydad #iloveme #lover #lovemygf #loveusis #love #gutlover #loveumom #uloveme #loveall #loveyoutoo #loveu2 #lomemymom #vsco',
    'landscape': '#landscape #amazing #view #trip #tree #sky #mountains #nature #landscape_lovers #landscapelovers #landscape_lover #landscapehunter #landscapes #landscapestyles #trees #treestagram #treescape #naturelovers #naturelover #nature_seekers #natureonly #nature_shooters #nature_prefection #naturediversity #naturephotography #naturewalk #naturegram #naturelove #naturephoto #vsco',
    'sky': '#skyfall #skyback #cloud9 #cloudporn #sky #blue #naturecloud_skye #skyporn #skypainters #skies #amazing #weather #clouds #cloudscape #cloud #dusk #instasky #skylovers #cloudstagram #view #naturelovers #gloomy #red #white #outside #light #sunset #epicsky #bluesky #vsco',
    'summer': '#summertime #summer #summernights #summerdays #summerfun #summerlovin #summerlove #summernight #summerfeeling #summerday #summerfashion #summerschool #beach #beachday #sea #beachlife #beachtime #swimsuit #hot #sunshine #sunshineaddicted #sunshineday #waves #ocean #instasummer #instasummer #vsco',
}
